# Generated by Django 6.1 on 2026-08-28 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_admission', models.DateTimeField(auto_now_add=True)),
                ('diagnostic', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CHEZ_LE_MEDECIN', 'Chez le médecin'), ('TERMINE', 'Terminé')], default='EN_ATTENTE', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150, verbose_name='Nom du patient')),
                ('doctor_name', models.CharField(max_length=150, verbose_name='Nom du médecin')),
                ('date', models.DateField(verbose_name='Date du rendez-vous')),
                ('time', models.TimeField(verbose_name='Heure du rendez-vous')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Motif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Constante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('tension', models.CharField(max_length=50)),
                ('glycemie', models.FloatField(blank=True, null=True)),
                ('degre_urgence', models.CharField(choices=[('ROUGE', 'Rouge'), ('JAUNE', 'Jaune'), ('VERT', 'Vert'), ('GRIS', 'Gris')], default='VERT', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constantes', to='clinic_app.admission')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('examen_clinique', models.TextField(blank=True, default='')),
                ('diagnostic', models.TextField(blank=True, default='')),
                ('remarques', models.TextField(blank=True, default='')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='clinic_app.admission')),
                ('medicaments', models.ManyToManyField(blank=True, related_name='consultations', to='clinic_app.medicament')),
            ],
        ),
        migrations.AddField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='clinic_app.patient'),
        ),
    ]
