# Generated by Django 6.1 on 2026-08-30 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='sexe',
            new_name='genre',
        ),
        migrations.AlterField(
            model_name='consultation',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.admission'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='diagnostic',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='examen_clinique',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='medicaments',
            field=models.ManyToManyField(blank=True, to='clinic_app.medicament'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='remarques',
            field=models.TextField(blank=True, null=True),
        ),
    ]
