# Generated by Django 6.1 on 2026-08-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150, verbose_name='اسم المريض')),
                ('doctor_name', models.CharField(max_length=150, verbose_name='اسم الطبيب')),
                ('date', models.DateField(verbose_name='تاريخ الموعد')),
                ('time', models.TimeField(verbose_name='وقت الموعد')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='سبب الزيارة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
