# Generated by Django 6.1 on 2026-08-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0002_rename_sexe_patient_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CHEZ_LE_MEDECIN', 'Chez le medecin'), ('TERMINE', 'Termine')], default='EN_ATTENTE', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnostic'),
        ),
    ]
