# Generated by Django 6.1.1 on 2026-09-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0004_remove_consultation_medicaments_ordonnance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1),
        ),
    ]
