# Generated by Django 6.1 on 2026-08-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0002_patient_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='motif',
            field=models.TextField(blank=True, null=True, verbose_name='Motif de consultation'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='examen_clinique',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='paye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constante',
            name='degre_urgence',
            field=models.CharField(choices=[('ROUGE', 'Urgent'), ('JAUNE', 'Moyen'), ('VERT', 'Normal'), ('GRIS', 'En attente')], default='VERT', max_length=10),
        ),
    ]
