# Generated by Django 6.1 on 2026-08-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0003_admission_motif_consultation_examen_clinique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constante',
            name='degre_urgence',
            field=models.CharField(choices=[('ROUGE', '🔴 Rouge (Urgent)'), ('JAUNE', '🟡 Jaune (Moyen)'), ('VERT', '🟢 Vert (Normal)'), ('GRIS', '⚪ Gris (En attente)')], default='VERT', max_length=10),
        ),
    ]
