# Generated by Django 6.1 on 2026-08-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0004_alter_constante_degre_urgence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Aux constantes', 'Aux constantes'), ('Chez le medecin', 'Chez le medecin'), ('Fini', 'Fini')], default='En attente', max_length=50),
        ),
    ]
